version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      timezone: 'America/Detroit'
    open-pull-requests-limit: 10
    reviewers:
      - 'team:Tech Lead'
    rebase-strategy: "disabled"
