name: Review Maint

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, ready_for_review, reopened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
    - name: Request review based on files changes and/or groups the author belongs to
      uses: necojackarc/auto-request-review@v0.13.0
      with:
        token: ${{ secrets.PAT_FOR_AUTO_REQUEST_REVIEW }}
        config: .github/reviewers.yaml
    